[package]
name = "portal-solutions-boople"
version = "0.1.0"
edition = "2024"
license = "MPL-2.0"
description = "One-off recreation of a state managemnt system for devices with limited input"

[dependencies]

[features]
unsize=[]
alloc=["unsize"]